# Generated by Django 3.2.1 on 2021-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('衛浴', '衛浴'), ('廚房', '廚房'), ('系統櫃', '系統櫃'), ('其他', '其他')], max_length=200, null=True),
        ),
    ]
