# Generated by Django 2.2.14 on 2021-05-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210516_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
